# Generated by Django 4.2.6 on 2023-10-16 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Order2',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Product2',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='User2',
        ),
    ]
